---
db_echo: True
api_log_path: montage_api.log
db_url: "sqlite:///tmp_montage.db"

cookie_secret: ReplaceThisWithSomethingSomewhatSecret
superuser: Slaporte

dev_local_cookie_value: "contact maintainers for details"
dev_remote_cookie_value: "contact maintainers for details"
oauth_client_id: "register an OAuth 2.0 consumer at https://meta.wikimedia.org/wiki/Special:OAuthConsumerRegistration/propose"
oauth_client_secret: "see note above"  # pragma: allowlist secret
oauth_redirect_uri: "http://localhost:5001/complete_login"
...
