services:
  montage:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    command: >
      bash -c "python tools/create_schema.py && python -m montage"
