services:
  montage:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  # Airplay runs on port 5000 on mac. See https://forums.developer.apple.com/forums/thread/682332
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    command: >
      bash -c "python tools/create_schema.py && python -m montage"
